# Toggles which actions should automatically add items to a player's inventory.
AutoPickup:
  Blocks: true
  Fishing: true
  Mobs: true

# Toggle true if you want to open automatic cook.
# This feature requires the permission autopickup.use.autocook
Settings:
  auto-cook: true

# Set if Auto Pickup should require permissions to use.
# If true, requires the permission autopickup.use
RequirePermission: false

# Settings that control the inventory full notification.
InventoryFull:
  # The message shown in chat when a player's inventory is full.
  # You can use hex colors by using & and the hex code. Ex: &#FFFF00
  Message: "&c&lYour Inventory Is Full!"

  # Plays a sound when the inventory full message is shown.
  # Full List of Sounds: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
  # Remove for no sound.
  Sound: BLOCK_NOTE_BLOCK_HARP