name: AutoPickup
version: '${project.version}'
main: net.jadedmc.autopickup.AutoPickupPlugin
api-version: 1.19
authors: [JadedMC]
description: Automatically Pick Up Items and Experience
website: https://www.jadedmc.net

softdepend:
  - BetterReload

commands:
  autopickup:
    description: AutoPickup plugin admin command.
    aliases: [pickup,ap]
    permission: autopickup.admin